version: '3'
services:
  libretv:
    image: bestzwei/zhuiju:latest
    container_name: zhuiju
    ports:
      - "8899:80"
    environment:
      - PASSWORD=${PASSWORD:-111111}
    restart: unless-stopped
